#!/usr/bin/env bash
#script that loops from 1 to 10 with bad good and best school
x=0
while [ $x -le 9 ]
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
