#!/usr/bin/env bash
# script to print from 1 to 20 and and other features
x=1

while [ "$x" -lt 21 ]; do
  
  case "$x" in
    4)
      echo "$x"
      echo "bad luck from China"
      ;;
    9)
      echo "$x"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$x"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$x"
      ;;
  esac

  ((x++))
done
