#!/usr/bin/env bash
# script to print from 1 to 20 and and other features
x=1
while [ $i -le 20 ]
do
	echo $x
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
		((x++))
done
