#!/usr/bin/env bash
# script displays time 12 hours and 59 minutes:

hour=0
minu=1
while [ $hour -le 12 ]; do
    echo "Hour: ${hour}"
    while [ $minu -lt 60 ]; do
	echo $minu
	let minu+=1
    done
    let minu=1
    let hour+=1
done
