#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01
# except the following TCP ports: TCP ports 22, 443 and 80.

sudo apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
